### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by ipkpjersi** [lavovaLampa/patreon-scraper#5]
Using Ubuntu 18.04 LTS with npm 6.13.4 and node v12.14.1
When I run it with `./index.ts`:
![](https://i.imgur.com/sG6YBdG.png)

When I run it with `node index.ts`: 
![](https://i.imgur.com/rYfdPoz.png)

When I run it with `tsc index.ts`:
![](https://i.imgur.com/xogqV5v.png)
![](https://i.imgur.com/lz88Usq.png)

**Comment by lavovaLampa** [comment]
It seems the '-S' switch for env is a fairly new addition ([info](https://github.com/jrudess/streamdvr/issues/118)). You can still start the script like this:

- `node -r ts-node/register index.ts`

I'll add the workaround to the README.

**Comment by ipkpjersi** [comment]
When I try running with `node -r ts-node/register index.ts` this happens:

![](https://i.imgur.com/ipwUn2x.png)
![](https://i.imgur.com/qBRLuCJ.png)

**Comment by lavovaLampa** [comment]
Try running:`npm update`
That should fix it.

**Comment by ipkpjersi** [comment]
I ran `npm update` and it did update modules but still I get the same errors.

**Comment by lavovaLampa** [comment]
The pre-packaged executables should be working in the 0.1.0 release.

**Comment by ipkpjersi** [comment]
Yep, the executable binary 0.1.0 works so we can probably close this issue. I still can't build it with Node 12 but at least I can run it.
